title: Freelancer
email: zebesquawz@gmail.com
url: 'http://dustinarmstrong.info'
description: >-
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
keywords: 'your keywords, separated by commas'
skills: Web Developer - Graphic Artist - Systems Administrator
meta_author: LastName FirstName
google_verify: null
bing_verify: null
contact: static
disqus_shortname: myshortname
color:
  primary: 18bc9c
  primary-rgb: '24,288,156'
  secondary: 2c3e50
  secondary-dark: 233140
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits
social:
  - title: twitter
    url: 'http://twitter.com/weathermakerco'
  - title: facebook
    url: 'https://www.facebook.com/dustin.armstrong.11.11'
  - title: stack-overflow
    url: 'http://stackoverflow.com/questions/tagged/weathermaker'
  - title: bitbucket
    url: 'http://bitbucket.org/weathermaker'
  - title: github
    url: 'http://github.com/weathermaker'
address:
  - line: 2469 W 1000 S
  - line: 'Williamsburg, IN 47393'
credits: >-
  Freelancer is a free to use, open source Bootstrap theme created by <a
  href="http://startbootstrap.com">Start Bootstrap</a>.
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-admin
